name = "RGTetra"                                                                        
location = "francecentral"
owner = "roumieux"
version = "1.44.0"

name_vnet = "testVnet"
address_space = [ "10.0.0.0/16" ]
name_subnet = "testSubnet"
address_prefix = "10.0.2.0/24"
nameNsg = "Nessenger"
namePubIp = "Fils2Pub"
allocation_method = "Dynamic"
nameNIC = "testNIC"
nameNICConfig = "testNICConfig"
nameVM = "testVM"
vmSize = "Standard_B1s"
